#!/bin/sh

#
# To install run the following from the .git/hooks folder
# ln -s ../../git-hooks/commit-msg commit-msg"
#

HAS_ERROR=0
ERROR=""

grep -Ehnq "^\((feat|hotfix|bugfix|fix|task|doc|docs|release|changelog|chore|refactor)\)+\s+(fix|fixes|fixed|close|closes|closed|resolve|resolves|resolved)?+\s?+\#([0-9]+|spelling|typo|whitespace|noticket)+\s" "$1"; RET=$?
if [ $RET -eq 1 ]; then
    HAS_ERROR=1
fi

if [ ${HAS_ERROR} = 1 ]; then
    ERROR="\nCommit message must be in format: (TYPE) #ISSUE SUMMARY\n"
    ERROR="${ERROR}  - TYPE: one of [feat|bugfix|fix|task|doc|docs|release|changelog|chore|refactor] *IN PARENS*\n"
    ERROR="${ERROR}          e.g. (feature)\n"
    ERROR="${ERROR}  - ISSUE: optional action [fix|fixes|fixed|close|closes|closed|resolve|resolves|resolved]\n"
    ERROR="${ERROR}           then #[github issue number|spelling|typo|whitespace]\n"
    ERROR="${ERROR}           e.g. \"closes #123\", \"#123\", \"#whitespace\" \n"
    ERROR="${ERROR}  - SUMMARY: short summary of issue\n"
    ERROR="${ERROR}\nLong description should be separated from SUMMARY with an empty line\n"
    echo ${ERROR} 1>&2
    exit 1
else
    exit 0
fi
