#!/bin/bash

#
# To install run the following from the .git/hooks folder
# ln -s ../../git-hooks/pre-commit pre-commit"
#

HAS_ERROR=0
ERROR=""
files=$(git diff-index --name-status --cached HEAD | grep -v ^D | cut -c3-)
if [ "$files" != "" ]; then
  for f in $files; do
    if [[ "$f" =~ [.](md|conf|css|erb|js|styl|erl|hrl|txt|xml|html|htm)$ ]]; then
        if [ "$(tail -c1 ${f})" != "\n" ]
        then
          echo "ERROR: \"${f}\" missing tailing newline at end of file"
          exit 1
        fi
    fi
  done
fi
exit 0
